version: 0.2

phases:

  install:

    runtime-versions:
      java: corretto17

  build:

    commands:

      - echo "Build Started"

      - mvn clean package

artifacts:

  files:

    - target/hello-world-lambda-1.0.jar
    - template.yaml