version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Build Started"
      - mvn clean package
      - echo "Packaging SAM template..."
      - aws cloudformation package
        --template-file template.yaml
        --s3-bucket vinay-lambda-artifacts
        --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml