AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Lambda inside VPC

Parameters:
  CognitoUserPoolArn:
    Type: String
    Default: "arn:aws:cognito-idp:us-east-1:006296771344:userpool/us-east-1_wK09KSLBQ"

Globals:
  Function:
    Runtime: java17
    MemorySize: 512
    Timeout: 30
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds:
        - subnet-043a7b786b6736129
        - subnet-0d81c6e86baf1f661

Resources:

  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: hello-world-api
      StageName: dev
      Description: !Sub "Deployed at ${AWS::StackName}"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
            Identity:
              Header: Authorization

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world-lambda
      Handler: com.vinay.vinayHandler::handleRequest
      CodeUri: target/hello-world-lambda-1.0.jar
      Role: !GetAtt HelloWorldLambdaRole.Arn
      Events:
        GetHello:
          Type: Api
          Properties:
            RestApiId: !Ref HelloWorldApi
            Path: /hello
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
              AuthorizationScopes:
                - vinay/read

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: hello-world-lambda-sg
      GroupDescription: Security group for Lambda
      VpcId: vpc-0929fb681224a00c4
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: Allow HTTPS outbound

  HelloWorldLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: hello-world-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

Outputs:
  ApiUrl:
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/dev/hello"
  LambdaArn:
    Value: !GetAtt HelloWorldFunction.Arn